Repository wecode-bootcamp-korea/29-1st-Apocalypse-backend, pull requests merged in 2022-01, with the labels that each got.

#2 [종말론] 모델링
  apocalypse/settings.py
  apocalypse/urls.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_rename_order_item_status_orderitemstatus_status_and_more.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/0002_alter_productcomponent_component_and_more.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/urls.py
  products/views.py
  services/__init__.py
  services/admin.py
  services/apps.py
  services/migrations/0001_initial.py
  services/migrations/0002_alter_reservation_shop_alter_reservation_user_and_more.py
  services/migrations/0003_remove_review_order_item_alter_review_product_and_more.py
  services/migrations/__init__.py
  services/models.py
  services/tests.py
  services/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/0002_remove_user_carts_remove_user_reviews_and_more.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 수정 요청, Status: 리뷰 요청

#4 [29기 이강일] 회원가입 및 로그인 구현
  apocalypse/settings.py
  apocalypse/urls.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/urls.py
  products/views.py
  services/migrations/0001_initial.py
  users/migrations/0001_initial.py
  users/urls.py
  users/views.py
Labels: Status: 수정 요청

#5 [Modify] 종말론 / 상품 카테고리 출력
  csv/categories.csv
  csv/images.csv
  csv/products.csv
  csv/subcategories.csv
  image_db_uploader.py
  product_db_uploader.py
  products/urls.py
  products/views.py
  users/urls.py
  users/views.py
Labels: Status: 수정 요청

#7 [29기 이강일] 제품 상세 페이지 API 구현
  .gitignore
  csv/.~lock.images.csv#
  csv/images.csv
  csv/products.csv
  csv/subcategories.csv
  products/views.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#6 [Modify] 상품 리스트 View, 모델링 수정
  .gitignore
  products/migrations/0002_subcategory_image_url.py
  products/models.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청
